use std::{fmt, io};
use ::libc;

pub enum SyscallName {
    Read,
    Write,
    Open,
    Close,
    Stat,
    Fstat,
    Lstat,
    Poll,
    Lseek,
    Mmap,
    Mprotect,
    Munmap,
    Brk,
    RtSigaction,
    RtSigprocmask,
    RtSigreturn,
    Ioctl,
    Pread64,
    Pwrite64,
    Readv,
    Writev,
    Access,
    Pipe,
    Select,
    SchedYield,
    Mremap,
    Msync,
    Mincore,
    Madvise,
    Shmget,
    Shmat,
    Shmctl,
    Dup,
    Dup2,
    Pause,
    Nanosleep,
    Getitimer,
    Alarm,
    Setitimer,
    Getpid,
    Sendfile,
    Socket,
    Connect,
    Accept,
    Sendto,
    Recvfrom,
    Sendmsg,
    Recvmsg,
    Shutdown,
    Bind,
    Listen,
    Getsockname,
    Getpeername,
    Socketpair,
    Setsockopt,
    Getsockopt,
    Clone,
    Fork,
    Vfork,
    Execve,
    Exit,
    Wait4,
    Kill,
    Uname,
    Semget,
    Semop,
    Semctl,
    Shmdt,
    Msgget,
    Msgsnd,
    Msgrcv,
    Msgctl,
    Fcntl,
    Flock,
    Fsync,
    Fdatasync,
    Truncate,
    Ftruncate,
    Getdents,
    Getcwd,
    Chdir,
    Fchdir,
    Rename,
    Mkdir,
    Rmdir,
    Creat,
    Link,
    Unlink,
    Symlink,
    Readlink,
    Chmod,
    Fchmod,
    Chown,
    Fchown,
    Lchown,
    Umask,
    Gettimeofday,
    Getrlimit,
    Getrusage,
    Sysinfo,
    Times,
    Ptrace,
    Getuid,
    Syslog,
    Getgid,
    Setuid,
    Setgid,
    Geteuid,
    Getegid,
    Setpgid,
    Getppid,
    Getpgrp,
    Setsid,
    Setreuid,
    Setregid,
    Getgroups,
    Setgroups,
    Setresuid,
    Getresuid,
    Setresgid,
    Getresgid,
    Getpgid,
    Setfsuid,
    Setfsgid,
    Getsid,
    Capget,
    Capset,
    RtSigpending,
    RtSigtimedwait,
    RtSigqueueinfo,
    RtSigsuspend,
    Sigaltstack,
    Utime,
    Mknod,
    Uselib,
    Personality,
    Ustat,
    Statfs,
    Fstatfs,
    Sysfs,
    Getpriority,
    Setpriority,
    SchedSetparam,
    SchedGetparam,
    SchedSetscheduler,
    SchedGetscheduler,
    SchedGetPriorityMax,
    SchedGetPriorityMin,
    SchedRrGetInterval,
    Mlock,
    Munlock,
    Mlockall,
    Munlockall,
    Vhangup,
    ModifyLdt,
    PivotRoot,
    Sysctl,
    Prctl,
    ArchPrctl,
    Adjtimex,
    Setrlimit,
    Chroot,
    Sync,
    Acct,
    Settimeofday,
    Mount,
    Umount2,
    Swapon,
    Swapoff,
    Reboot,
    Sethostname,
    Setdomainname,
    Iopl,
    Ioperm,
    CreateModule,
    InitModule,
    DeleteModule,
    GetKernelSyms,
    QueryModule,
    Quotactl,
    Nfsservctl,
    Getpmsg,
    Putpmsg,
    AfsSyscall,
    Tuxcall,
    Security,
    Gettid,
    Readahead,
    Setxattr,
    Lsetxattr,
    Fsetxattr,
    Getxattr,
    Lgetxattr,
    Fgetxattr,
    Listxattr,
    Llistxattr,
    Flistxattr,
    Removexattr,
    Lremovexattr,
    Fremovexattr,
    Tkill,
    Time,
    Futex,
    SchedSetaffinity,
    SchedGetaffinity,
    SetThreadArea,
    IoSetup,
    IoDestroy,
    IoGetevents,
    IoSubmit,
    IoCancel,
    GetThreadArea,
    LookupDcookie,
    EpollCreate,
    EpollCtlPld,
    EpollWaitPld,
    RemapFilePages,
    Getdents64,
    SetTidAddress,
    RestartSyscall,
    Semtimedop,
    Fadvise64,
    TimerCreate,
    TimerSettime,
    TimerGettime,
    TimerGetoverrun,
    TimerDelete,
    ClockSettime,
    ClockGettime,
    ClockGetres,
    ClockNanosleep,
    ExitGroup,
    EpollWait,
    EpollCtl,
    Tgkill,
    Utimes,
    Vserver,
    Mbind,
    SetMempolicy,
    GetMempolicy,
    MqOpen,
    MqUnlink,
    MqTimedsend,
    MqTimedreceive,
    MqNotify,
    MqGetsetattr,
    KexecLoad,
    Waitid,
    AddKey,
    RequestKey,
    Keyctl,
    IoprioSet,
    IoprioGet,
    InotifyInit,
    InotifyAddWatch,
    InotifyRmWatch,
    MigratePages,
    Openat,
    Mkdirat,
    Mknodat,
    Fchownat,
    Futimesat,
    Newfstatat,
    Unlinkat,
    Renameat,
    Linkat,
    Symlinkat,
    Readlinkat,
    Fchmodat,
    Faccessat,
    Pselect6,
    Ppoll,
    Unshare,
    SetRobustList,
    GetRobustList,
    Splice,
    Tee,
    SyncFileRange,
    Vmsplice,
    MovePages,
    Utimensat,
    EpollPwait,
    Signalfd,
    TimerfdCreate,
    Eventfd,
    Fallocate,
    TimerfdSettime,
    TimerfdGettime,
    Accept4,
    Signalfd4,
    Eventfd2,
    EpollCreate1,
    Dup3,
    Pipe2,
    InotifyInit1,
    Preadv,
    Pwritev,
    RtTgsigqueueinfo,
    PerfEventOpen,
    Recvmmsg,
    FanotifyInit,
    FanotifyMark,
    Prlimit64,
    NameToHandleAt,
    OpenByHandleAt,
    ClockAdjtime,
    Syncfs,
    Sendmmsg,
    Setns,
    Getcpu,
    ProcessVmReadv,
    ProcessVmWritev,
    Kcmp,
    FinitModule,
    SchedSetattr,
    SchedGetattr,
    Renameat2,
    Seccomp,
    Getrandom,
    MemfdCreate,
    KexecFileLoad,
    Bpf,
    Execveat,
    Userfaultfd,
    Membarrier,
    Mlock2,
    CopyFileRange,
    Preadv2,
    Pwritev2,
}

impl SyscallName {
    pub fn new(syscall: libc::c_ulong) -> io::Result<Self> {
        match syscall {
            0 => Ok(SyscallName::Read),
            1 => Ok(SyscallName::Write),
            2 => Ok(SyscallName::Open),
            3 => Ok(SyscallName::Close),
            4 => Ok(SyscallName::Stat),
            5 => Ok(SyscallName::Fstat),
            6 => Ok(SyscallName::Lstat),
            7 => Ok(SyscallName::Poll),
            8 => Ok(SyscallName::Lseek),
            9 => Ok(SyscallName::Mmap),
            10 => Ok(SyscallName::Mprotect),
            11 => Ok(SyscallName::Munmap),
            12 => Ok(SyscallName::Brk),
            13 => Ok(SyscallName::RtSigaction),
            14 => Ok(SyscallName::RtSigprocmask),
            15 => Ok(SyscallName::RtSigreturn),
            16 => Ok(SyscallName::Ioctl),
            17 => Ok(SyscallName::Pread64),
            18 => Ok(SyscallName::Pwrite64),
            19 => Ok(SyscallName::Readv),
            20 => Ok(SyscallName::Writev),
            21 => Ok(SyscallName::Access),
            22 => Ok(SyscallName::Pipe),
            23 => Ok(SyscallName::Select),
            24 => Ok(SyscallName::SchedYield),
            25 => Ok(SyscallName::Mremap),
            26 => Ok(SyscallName::Msync),
            27 => Ok(SyscallName::Mincore),
            28 => Ok(SyscallName::Madvise),
            29 => Ok(SyscallName::Shmget),
            30 => Ok(SyscallName::Shmat),
            31 => Ok(SyscallName::Shmctl),
            32 => Ok(SyscallName::Dup),
            33 => Ok(SyscallName::Dup2),
            34 => Ok(SyscallName::Pause),
            35 => Ok(SyscallName::Nanosleep),
            36 => Ok(SyscallName::Getitimer),
            37 => Ok(SyscallName::Alarm),
            38 => Ok(SyscallName::Setitimer),
            39 => Ok(SyscallName::Getpid),
            40 => Ok(SyscallName::Sendfile),
            41 => Ok(SyscallName::Socket),
            42 => Ok(SyscallName::Connect),
            43 => Ok(SyscallName::Accept),
            44 => Ok(SyscallName::Sendto),
            45 => Ok(SyscallName::Recvfrom),
            46 => Ok(SyscallName::Sendmsg),
            47 => Ok(SyscallName::Recvmsg),
            48 => Ok(SyscallName::Shutdown),
            49 => Ok(SyscallName::Bind),
            50 => Ok(SyscallName::Listen),
            51 => Ok(SyscallName::Getsockname),
            52 => Ok(SyscallName::Getpeername),
            53 => Ok(SyscallName::Socketpair),
            54 => Ok(SyscallName::Setsockopt),
            55 => Ok(SyscallName::Getsockopt),
            56 => Ok(SyscallName::Clone),
            57 => Ok(SyscallName::Fork),
            58 => Ok(SyscallName::Vfork),
            59 => Ok(SyscallName::Execve),
            60 => Ok(SyscallName::Exit),
            61 => Ok(SyscallName::Wait4),
            62 => Ok(SyscallName::Kill),
            63 => Ok(SyscallName::Uname),
            64 => Ok(SyscallName::Semget),
            65 => Ok(SyscallName::Semop),
            66 => Ok(SyscallName::Semctl),
            67 => Ok(SyscallName::Shmdt),
            68 => Ok(SyscallName::Msgget),
            69 => Ok(SyscallName::Msgsnd),
            70 => Ok(SyscallName::Msgrcv),
            71 => Ok(SyscallName::Msgctl),
            72 => Ok(SyscallName::Fcntl),
            73 => Ok(SyscallName::Flock),
            74 => Ok(SyscallName::Fsync),
            75 => Ok(SyscallName::Fdatasync),
            76 => Ok(SyscallName::Truncate),
            77 => Ok(SyscallName::Ftruncate),
            78 => Ok(SyscallName::Getdents),
            79 => Ok(SyscallName::Getcwd),
            80 => Ok(SyscallName::Chdir),
            81 => Ok(SyscallName::Fchdir),
            82 => Ok(SyscallName::Rename),
            83 => Ok(SyscallName::Mkdir),
            84 => Ok(SyscallName::Rmdir),
            85 => Ok(SyscallName::Creat),
            86 => Ok(SyscallName::Link),
            87 => Ok(SyscallName::Unlink),
            88 => Ok(SyscallName::Symlink),
            89 => Ok(SyscallName::Readlink),
            90 => Ok(SyscallName::Chmod),
            91 => Ok(SyscallName::Fchmod),
            92 => Ok(SyscallName::Chown),
            93 => Ok(SyscallName::Fchown),
            94 => Ok(SyscallName::Lchown),
            95 => Ok(SyscallName::Umask),
            96 => Ok(SyscallName::Gettimeofday),
            97 => Ok(SyscallName::Getrlimit),
            98 => Ok(SyscallName::Getrusage),
            99 => Ok(SyscallName::Sysinfo),
            100 => Ok(SyscallName::Times),
            101 => Ok(SyscallName::Ptrace),
            102 => Ok(SyscallName::Getuid),
            103 => Ok(SyscallName::Syslog),
            104 => Ok(SyscallName::Getgid),
            105 => Ok(SyscallName::Setuid),
            106 => Ok(SyscallName::Setgid),
            107 => Ok(SyscallName::Geteuid),
            108 => Ok(SyscallName::Getegid),
            109 => Ok(SyscallName::Setpgid),
            110 => Ok(SyscallName::Getppid),
            111 => Ok(SyscallName::Getpgrp),
            112 => Ok(SyscallName::Setsid),
            113 => Ok(SyscallName::Setreuid),
            114 => Ok(SyscallName::Setregid),
            115 => Ok(SyscallName::Getgroups),
            116 => Ok(SyscallName::Setgroups),
            117 => Ok(SyscallName::Setresuid),
            118 => Ok(SyscallName::Getresuid),
            119 => Ok(SyscallName::Setresgid),
            120 => Ok(SyscallName::Getresgid),
            121 => Ok(SyscallName::Getpgid),
            122 => Ok(SyscallName::Setfsuid),
            123 => Ok(SyscallName::Setfsgid),
            124 => Ok(SyscallName::Getsid),
            125 => Ok(SyscallName::Capget),
            126 => Ok(SyscallName::Capset),
            127 => Ok(SyscallName::RtSigpending),
            128 => Ok(SyscallName::RtSigtimedwait),
            129 => Ok(SyscallName::RtSigqueueinfo),
            130 => Ok(SyscallName::RtSigsuspend),
            131 => Ok(SyscallName::Sigaltstack),
            132 => Ok(SyscallName::Utime),
            133 => Ok(SyscallName::Mknod),
            134 => Ok(SyscallName::Uselib),
            135 => Ok(SyscallName::Personality),
            136 => Ok(SyscallName::Ustat),
            137 => Ok(SyscallName::Statfs),
            138 => Ok(SyscallName::Fstatfs),
            139 => Ok(SyscallName::Sysfs),
            140 => Ok(SyscallName::Getpriority),
            141 => Ok(SyscallName::Setpriority),
            142 => Ok(SyscallName::SchedSetparam),
            143 => Ok(SyscallName::SchedGetparam),
            144 => Ok(SyscallName::SchedSetscheduler),
            145 => Ok(SyscallName::SchedGetscheduler),
            146 => Ok(SyscallName::SchedGetPriorityMax),
            147 => Ok(SyscallName::SchedGetPriorityMin),
            148 => Ok(SyscallName::SchedRrGetInterval),
            149 => Ok(SyscallName::Mlock),
            150 => Ok(SyscallName::Munlock),
            151 => Ok(SyscallName::Mlockall),
            152 => Ok(SyscallName::Munlockall),
            153 => Ok(SyscallName::Vhangup),
            154 => Ok(SyscallName::ModifyLdt),
            155 => Ok(SyscallName::PivotRoot),
            156 => Ok(SyscallName::Sysctl),
            157 => Ok(SyscallName::Prctl),
            158 => Ok(SyscallName::ArchPrctl),
            159 => Ok(SyscallName::Adjtimex),
            160 => Ok(SyscallName::Setrlimit),
            161 => Ok(SyscallName::Chroot),
            162 => Ok(SyscallName::Sync),
            163 => Ok(SyscallName::Acct),
            164 => Ok(SyscallName::Settimeofday),
            165 => Ok(SyscallName::Mount),
            166 => Ok(SyscallName::Umount2),
            167 => Ok(SyscallName::Swapon),
            168 => Ok(SyscallName::Swapoff),
            169 => Ok(SyscallName::Reboot),
            170 => Ok(SyscallName::Sethostname),
            171 => Ok(SyscallName::Setdomainname),
            172 => Ok(SyscallName::Iopl),
            173 => Ok(SyscallName::Ioperm),
            174 => Ok(SyscallName::CreateModule),
            175 => Ok(SyscallName::InitModule),
            176 => Ok(SyscallName::DeleteModule),
            177 => Ok(SyscallName::GetKernelSyms),
            178 => Ok(SyscallName::QueryModule),
            179 => Ok(SyscallName::Quotactl),
            180 => Ok(SyscallName::Nfsservctl),
            181 => Ok(SyscallName::Getpmsg),
            182 => Ok(SyscallName::Putpmsg),
            183 => Ok(SyscallName::AfsSyscall),
            184 => Ok(SyscallName::Tuxcall),
            185 => Ok(SyscallName::Security),
            186 => Ok(SyscallName::Gettid),
            187 => Ok(SyscallName::Readahead),
            188 => Ok(SyscallName::Setxattr),
            189 => Ok(SyscallName::Lsetxattr),
            190 => Ok(SyscallName::Fsetxattr),
            191 => Ok(SyscallName::Getxattr),
            192 => Ok(SyscallName::Lgetxattr),
            193 => Ok(SyscallName::Fgetxattr),
            194 => Ok(SyscallName::Listxattr),
            195 => Ok(SyscallName::Llistxattr),
            196 => Ok(SyscallName::Flistxattr),
            197 => Ok(SyscallName::Removexattr),
            198 => Ok(SyscallName::Lremovexattr),
            199 => Ok(SyscallName::Fremovexattr),
            200 => Ok(SyscallName::Tkill),
            201 => Ok(SyscallName::Time),
            202 => Ok(SyscallName::Futex),
            203 => Ok(SyscallName::SchedSetaffinity),
            204 => Ok(SyscallName::SchedGetaffinity),
            205 => Ok(SyscallName::SetThreadArea),
            206 => Ok(SyscallName::IoSetup),
            207 => Ok(SyscallName::IoDestroy),
            208 => Ok(SyscallName::IoGetevents),
            209 => Ok(SyscallName::IoSubmit),
            210 => Ok(SyscallName::IoCancel),
            211 => Ok(SyscallName::GetThreadArea),
            212 => Ok(SyscallName::LookupDcookie),
            213 => Ok(SyscallName::EpollCreate),
            214 => Ok(SyscallName::EpollCtlPld),
            215 => Ok(SyscallName::EpollWaitPld),
            216 => Ok(SyscallName::RemapFilePages),
            217 => Ok(SyscallName::Getdents64),
            218 => Ok(SyscallName::SetTidAddress),
            219 => Ok(SyscallName::RestartSyscall),
            220 => Ok(SyscallName::Semtimedop),
            221 => Ok(SyscallName::Fadvise64),
            222 => Ok(SyscallName::TimerCreate),
            223 => Ok(SyscallName::TimerSettime),
            224 => Ok(SyscallName::TimerGettime),
            225 => Ok(SyscallName::TimerGetoverrun),
            226 => Ok(SyscallName::TimerDelete),
            227 => Ok(SyscallName::ClockSettime),
            228 => Ok(SyscallName::ClockGettime),
            229 => Ok(SyscallName::ClockGetres),
            230 => Ok(SyscallName::ClockNanosleep),
            231 => Ok(SyscallName::ExitGroup),
            232 => Ok(SyscallName::EpollWait),
            233 => Ok(SyscallName::EpollCtl),
            234 => Ok(SyscallName::Tgkill),
            235 => Ok(SyscallName::Utimes),
            236 => Ok(SyscallName::Vserver),
            237 => Ok(SyscallName::Mbind),
            238 => Ok(SyscallName::SetMempolicy),
            239 => Ok(SyscallName::GetMempolicy),
            240 => Ok(SyscallName::MqOpen),
            241 => Ok(SyscallName::MqUnlink),
            242 => Ok(SyscallName::MqTimedsend),
            243 => Ok(SyscallName::MqTimedreceive),
            244 => Ok(SyscallName::MqNotify),
            245 => Ok(SyscallName::MqGetsetattr),
            246 => Ok(SyscallName::KexecLoad),
            247 => Ok(SyscallName::Waitid),
            248 => Ok(SyscallName::AddKey),
            249 => Ok(SyscallName::RequestKey),
            250 => Ok(SyscallName::Keyctl),
            251 => Ok(SyscallName::IoprioSet),
            252 => Ok(SyscallName::IoprioGet),
            253 => Ok(SyscallName::InotifyInit),
            254 => Ok(SyscallName::InotifyAddWatch),
            255 => Ok(SyscallName::InotifyRmWatch),
            256 => Ok(SyscallName::MigratePages),
            257 => Ok(SyscallName::Openat),
            258 => Ok(SyscallName::Mkdirat),
            259 => Ok(SyscallName::Mknodat),
            260 => Ok(SyscallName::Fchownat),
            261 => Ok(SyscallName::Futimesat),
            262 => Ok(SyscallName::Newfstatat),
            263 => Ok(SyscallName::Unlinkat),
            264 => Ok(SyscallName::Renameat),
            265 => Ok(SyscallName::Linkat),
            266 => Ok(SyscallName::Symlinkat),
            267 => Ok(SyscallName::Readlinkat),
            268 => Ok(SyscallName::Fchmodat),
            269 => Ok(SyscallName::Faccessat),
            270 => Ok(SyscallName::Pselect6),
            271 => Ok(SyscallName::Ppoll),
            272 => Ok(SyscallName::Unshare),
            273 => Ok(SyscallName::SetRobustList),
            274 => Ok(SyscallName::GetRobustList),
            275 => Ok(SyscallName::Splice),
            276 => Ok(SyscallName::Tee),
            277 => Ok(SyscallName::SyncFileRange),
            278 => Ok(SyscallName::Vmsplice),
            279 => Ok(SyscallName::MovePages),
            280 => Ok(SyscallName::Utimensat),
            281 => Ok(SyscallName::EpollPwait),
            282 => Ok(SyscallName::Signalfd),
            283 => Ok(SyscallName::TimerfdCreate),
            284 => Ok(SyscallName::Eventfd),
            285 => Ok(SyscallName::Fallocate),
            286 => Ok(SyscallName::TimerfdSettime),
            287 => Ok(SyscallName::TimerfdGettime),
            288 => Ok(SyscallName::Accept4),
            289 => Ok(SyscallName::Signalfd4),
            290 => Ok(SyscallName::Eventfd2),
            291 => Ok(SyscallName::EpollCreate1),
            292 => Ok(SyscallName::Dup3),
            293 => Ok(SyscallName::Pipe2),
            294 => Ok(SyscallName::InotifyInit1),
            295 => Ok(SyscallName::Preadv),
            296 => Ok(SyscallName::Pwritev),
            297 => Ok(SyscallName::RtTgsigqueueinfo),
            298 => Ok(SyscallName::PerfEventOpen),
            299 => Ok(SyscallName::Recvmmsg),
            300 => Ok(SyscallName::FanotifyInit),
            301 => Ok(SyscallName::FanotifyMark),
            302 => Ok(SyscallName::Prlimit64),
            303 => Ok(SyscallName::NameToHandleAt),
            304 => Ok(SyscallName::OpenByHandleAt),
            305 => Ok(SyscallName::ClockAdjtime),
            306 => Ok(SyscallName::Syncfs),
            307 => Ok(SyscallName::Sendmmsg),
            308 => Ok(SyscallName::Setns),
            309 => Ok(SyscallName::Getcpu),
            310 => Ok(SyscallName::ProcessVmReadv),
            311 => Ok(SyscallName::ProcessVmWritev),
            312 => Ok(SyscallName::Kcmp),
            313 => Ok(SyscallName::FinitModule),
            314 => Ok(SyscallName::SchedSetattr),
            315 => Ok(SyscallName::SchedGetattr),
            316 => Ok(SyscallName::Renameat2),
            317 => Ok(SyscallName::Seccomp),
            318 => Ok(SyscallName::Getrandom),
            319 => Ok(SyscallName::MemfdCreate),
            320 => Ok(SyscallName::KexecFileLoad),
            321 => Ok(SyscallName::Bpf),
            322 => Ok(SyscallName::Execveat),
            323 => Ok(SyscallName::Userfaultfd),
            324 => Ok(SyscallName::Membarrier),
            325 => Ok(SyscallName::Mlock2),
            326 => Ok(SyscallName::CopyFileRange),
            327 => Ok(SyscallName::Preadv2),
            328 => Ok(SyscallName::Pwritev2),
            _ => unimplemented!(),
        }
    }
}

impl fmt::Display for SyscallName {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match *self {
            SyscallName::Read => write!(f, "{}", "read"),
            SyscallName::Write => write!(f, "{}", "write"),
            SyscallName::Open => write!(f, "{}", "open"),
            SyscallName::Close => write!(f, "{}", "close"),
            SyscallName::Stat => write!(f, "{}", "stat"),
            SyscallName::Fstat => write!(f, "{}", "fstat"),
            SyscallName::Lstat => write!(f, "{}", "lstat"),
            SyscallName::Poll => write!(f, "{}", "poll"),
            SyscallName::Lseek => write!(f, "{}", "lseek"),
            SyscallName::Mmap => write!(f, "{}", "mmap"),
            SyscallName::Mprotect => write!(f, "{}", "mprotect"),
            SyscallName::Munmap => write!(f, "{}", "munmap"),
            SyscallName::Brk => write!(f, "{}", "brk"),
            SyscallName::RtSigaction => write!(f, "{}", "rtsigaction"),
            SyscallName::RtSigprocmask => write!(f, "{}", "rtsigprocmask"),
            SyscallName::RtSigreturn => write!(f, "{}", "rtsigreturn"),
            SyscallName::Ioctl => write!(f, "{}", "ioctl"),
            SyscallName::Pread64 => write!(f, "{}", "pread64"),
            SyscallName::Pwrite64 => write!(f, "{}", "pwrite64"),
            SyscallName::Readv => write!(f, "{}", "readv"),
            SyscallName::Writev => write!(f, "{}", "writev"),
            SyscallName::Access => write!(f, "{}", "access"),
            SyscallName::Pipe => write!(f, "{}", "pipe"),
            SyscallName::Select => write!(f, "{}", "select"),
            SyscallName::SchedYield => write!(f, "{}", "schedyield"),
            SyscallName::Mremap => write!(f, "{}", "mremap"),
            SyscallName::Msync => write!(f, "{}", "msync"),
            SyscallName::Mincore => write!(f, "{}", "mincore"),
            SyscallName::Madvise => write!(f, "{}", "madvise"),
            SyscallName::Shmget => write!(f, "{}", "shmget"),
            SyscallName::Shmat => write!(f, "{}", "shmat"),
            SyscallName::Shmctl => write!(f, "{}", "shmctl"),
            SyscallName::Dup => write!(f, "{}", "dup"),
            SyscallName::Dup2 => write!(f, "{}", "dup2"),
            SyscallName::Pause => write!(f, "{}", "pause"),
            SyscallName::Nanosleep => write!(f, "{}", "nanosleep"),
            SyscallName::Getitimer => write!(f, "{}", "getitimer"),
            SyscallName::Alarm => write!(f, "{}", "alarm"),
            SyscallName::Setitimer => write!(f, "{}", "setitimer"),
            SyscallName::Getpid => write!(f, "{}", "getpid"),
            SyscallName::Sendfile => write!(f, "{}", "sendfile"),
            SyscallName::Socket => write!(f, "{}", "socket"),
            SyscallName::Connect => write!(f, "{}", "connect"),
            SyscallName::Accept => write!(f, "{}", "accept"),
            SyscallName::Sendto => write!(f, "{}", "sendto"),
            SyscallName::Recvfrom => write!(f, "{}", "recvfrom"),
            SyscallName::Sendmsg => write!(f, "{}", "sendmsg"),
            SyscallName::Recvmsg => write!(f, "{}", "recvmsg"),
            SyscallName::Shutdown => write!(f, "{}", "shutdown"),
            SyscallName::Bind => write!(f, "{}", "bind"),
            SyscallName::Listen => write!(f, "{}", "listen"),
            SyscallName::Getsockname => write!(f, "{}", "getsockname"),
            SyscallName::Getpeername => write!(f, "{}", "getpeername"),
            SyscallName::Socketpair => write!(f, "{}", "socketpair"),
            SyscallName::Setsockopt => write!(f, "{}", "setsockopt"),
            SyscallName::Getsockopt => write!(f, "{}", "getsockopt"),
            SyscallName::Clone => write!(f, "{}", "clone"),
            SyscallName::Fork => write!(f, "{}", "fork"),
            SyscallName::Vfork => write!(f, "{}", "vfork"),
            SyscallName::Execve => write!(f, "{}", "execve"),
            SyscallName::Exit => write!(f, "{}", "exit"),
            SyscallName::Wait4 => write!(f, "{}", "wait4"),
            SyscallName::Kill => write!(f, "{}", "kill"),
            SyscallName::Uname => write!(f, "{}", "uname"),
            SyscallName::Semget => write!(f, "{}", "semget"),
            SyscallName::Semop => write!(f, "{}", "semop"),
            SyscallName::Semctl => write!(f, "{}", "semctl"),
            SyscallName::Shmdt => write!(f, "{}", "shmdt"),
            SyscallName::Msgget => write!(f, "{}", "msgget"),
            SyscallName::Msgsnd => write!(f, "{}", "msgsnd"),
            SyscallName::Msgrcv => write!(f, "{}", "msgrcv"),
            SyscallName::Msgctl => write!(f, "{}", "msgctl"),
            SyscallName::Fcntl => write!(f, "{}", "fcntl"),
            SyscallName::Flock => write!(f, "{}", "flock"),
            SyscallName::Fsync => write!(f, "{}", "fsync"),
            SyscallName::Fdatasync => write!(f, "{}", "fdatasync"),
            SyscallName::Truncate => write!(f, "{}", "truncate"),
            SyscallName::Ftruncate => write!(f, "{}", "ftruncate"),
            SyscallName::Getdents => write!(f, "{}", "getdents"),
            SyscallName::Getcwd => write!(f, "{}", "getcwd"),
            SyscallName::Chdir => write!(f, "{}", "chdir"),
            SyscallName::Fchdir => write!(f, "{}", "fchdir"),
            SyscallName::Rename => write!(f, "{}", "rename"),
            SyscallName::Mkdir => write!(f, "{}", "mkdir"),
            SyscallName::Rmdir => write!(f, "{}", "rmdir"),
            SyscallName::Creat => write!(f, "{}", "creat"),
            SyscallName::Link => write!(f, "{}", "link"),
            SyscallName::Unlink => write!(f, "{}", "unlink"),
            SyscallName::Symlink => write!(f, "{}", "symlink"),
            SyscallName::Readlink => write!(f, "{}", "readlink"),
            SyscallName::Chmod => write!(f, "{}", "chmod"),
            SyscallName::Fchmod => write!(f, "{}", "fchmod"),
            SyscallName::Chown => write!(f, "{}", "chown"),
            SyscallName::Fchown => write!(f, "{}", "fchown"),
            SyscallName::Lchown => write!(f, "{}", "lchown"),
            SyscallName::Umask => write!(f, "{}", "umask"),
            SyscallName::Gettimeofday => write!(f, "{}", "gettimeofday"),
            SyscallName::Getrlimit => write!(f, "{}", "getrlimit"),
            SyscallName::Getrusage => write!(f, "{}", "getrusage"),
            SyscallName::Sysinfo => write!(f, "{}", "sysinfo"),
            SyscallName::Times => write!(f, "{}", "times"),
            SyscallName::Ptrace => write!(f, "{}", "ptrace"),
            SyscallName::Getuid => write!(f, "{}", "getuid"),
            SyscallName::Syslog => write!(f, "{}", "syslog"),
            SyscallName::Getgid => write!(f, "{}", "getgid"),
            SyscallName::Setuid => write!(f, "{}", "setuid"),
            SyscallName::Setgid => write!(f, "{}", "setgid"),
            SyscallName::Geteuid => write!(f, "{}", "geteuid"),
            SyscallName::Getegid => write!(f, "{}", "getegid"),
            SyscallName::Setpgid => write!(f, "{}", "setpgid"),
            SyscallName::Getppid => write!(f, "{}", "getppid"),
            SyscallName::Getpgrp => write!(f, "{}", "getpgrp"),
            SyscallName::Setsid => write!(f, "{}", "setsid"),
            SyscallName::Setreuid => write!(f, "{}", "setreuid"),
            SyscallName::Setregid => write!(f, "{}", "setregid"),
            SyscallName::Getgroups => write!(f, "{}", "getgroups"),
            SyscallName::Setgroups => write!(f, "{}", "setgroups"),
            SyscallName::Setresuid => write!(f, "{}", "setresuid"),
            SyscallName::Getresuid => write!(f, "{}", "getresuid"),
            SyscallName::Setresgid => write!(f, "{}", "setresgid"),
            SyscallName::Getresgid => write!(f, "{}", "getresgid"),
            SyscallName::Getpgid => write!(f, "{}", "getpgid"),
            SyscallName::Setfsuid => write!(f, "{}", "setfsuid"),
            SyscallName::Setfsgid => write!(f, "{}", "setfsgid"),
            SyscallName::Getsid => write!(f, "{}", "getsid"),
            SyscallName::Capget => write!(f, "{}", "capget"),
            SyscallName::Capset => write!(f, "{}", "capset"),
            SyscallName::RtSigpending => write!(f, "{}", "rtsigpending"),
            SyscallName::RtSigtimedwait => write!(f, "{}", "rtsigtimedwait"),
            SyscallName::RtSigqueueinfo => write!(f, "{}", "rtsigqueueinfo"),
            SyscallName::RtSigsuspend => write!(f, "{}", "rtsigsuspend"),
            SyscallName::Sigaltstack => write!(f, "{}", "sigaltstack"),
            SyscallName::Utime => write!(f, "{}", "utime"),
            SyscallName::Mknod => write!(f, "{}", "mknod"),
            SyscallName::Uselib => write!(f, "{}", "uselib"),
            SyscallName::Personality => write!(f, "{}", "personality"),
            SyscallName::Ustat => write!(f, "{}", "ustat"),
            SyscallName::Statfs => write!(f, "{}", "statfs"),
            SyscallName::Fstatfs => write!(f, "{}", "fstatfs"),
            SyscallName::Sysfs => write!(f, "{}", "sysfs"),
            SyscallName::Getpriority => write!(f, "{}", "getpriority"),
            SyscallName::Setpriority => write!(f, "{}", "setpriority"),
            SyscallName::SchedSetparam => write!(f, "{}", "schedsetparam"),
            SyscallName::SchedGetparam => write!(f, "{}", "schedgetparam"),
            SyscallName::SchedSetscheduler => write!(f, "{}", "schedsetscheduler"),
            SyscallName::SchedGetscheduler => write!(f, "{}", "schedgetscheduler"),
            SyscallName::SchedGetPriorityMax => write!(f, "{}", "schedgetprioritymax"),
            SyscallName::SchedGetPriorityMin => write!(f, "{}", "schedgetprioritymin"),
            SyscallName::SchedRrGetInterval => write!(f, "{}", "schedrrgetinterval"),
            SyscallName::Mlock => write!(f, "{}", "mlock"),
            SyscallName::Munlock => write!(f, "{}", "munlock"),
            SyscallName::Mlockall => write!(f, "{}", "mlockall"),
            SyscallName::Munlockall => write!(f, "{}", "munlockall"),
            SyscallName::Vhangup => write!(f, "{}", "vhangup"),
            SyscallName::ModifyLdt => write!(f, "{}", "modifyldt"),
            SyscallName::PivotRoot => write!(f, "{}", "pivotroot"),
            SyscallName::Sysctl => write!(f, "{}", "sysctl"),
            SyscallName::Prctl => write!(f, "{}", "prctl"),
            SyscallName::ArchPrctl => write!(f, "{}", "archprctl"),
            SyscallName::Adjtimex => write!(f, "{}", "adjtimex"),
            SyscallName::Setrlimit => write!(f, "{}", "setrlimit"),
            SyscallName::Chroot => write!(f, "{}", "chroot"),
            SyscallName::Sync => write!(f, "{}", "sync"),
            SyscallName::Acct => write!(f, "{}", "acct"),
            SyscallName::Settimeofday => write!(f, "{}", "settimeofday"),
            SyscallName::Mount => write!(f, "{}", "mount"),
            SyscallName::Umount2 => write!(f, "{}", "umount2"),
            SyscallName::Swapon => write!(f, "{}", "swapon"),
            SyscallName::Swapoff => write!(f, "{}", "swapoff"),
            SyscallName::Reboot => write!(f, "{}", "reboot"),
            SyscallName::Sethostname => write!(f, "{}", "sethostname"),
            SyscallName::Setdomainname => write!(f, "{}", "setdomainname"),
            SyscallName::Iopl => write!(f, "{}", "iopl"),
            SyscallName::Ioperm => write!(f, "{}", "ioperm"),
            SyscallName::CreateModule => write!(f, "{}", "createmodule"),
            SyscallName::InitModule => write!(f, "{}", "initmodule"),
            SyscallName::DeleteModule => write!(f, "{}", "deletemodule"),
            SyscallName::GetKernelSyms => write!(f, "{}", "getkernelsyms"),
            SyscallName::QueryModule => write!(f, "{}", "querymodule"),
            SyscallName::Quotactl => write!(f, "{}", "quotactl"),
            SyscallName::Nfsservctl => write!(f, "{}", "nfsservctl"),
            SyscallName::Getpmsg => write!(f, "{}", "getpmsg"),
            SyscallName::Putpmsg => write!(f, "{}", "putpmsg"),
            SyscallName::AfsSyscall => write!(f, "{}", "afssyscall"),
            SyscallName::Tuxcall => write!(f, "{}", "tuxcall"),
            SyscallName::Security => write!(f, "{}", "security"),
            SyscallName::Gettid => write!(f, "{}", "gettid"),
            SyscallName::Readahead => write!(f, "{}", "readahead"),
            SyscallName::Setxattr => write!(f, "{}", "setxattr"),
            SyscallName::Lsetxattr => write!(f, "{}", "lsetxattr"),
            SyscallName::Fsetxattr => write!(f, "{}", "fsetxattr"),
            SyscallName::Getxattr => write!(f, "{}", "getxattr"),
            SyscallName::Lgetxattr => write!(f, "{}", "lgetxattr"),
            SyscallName::Fgetxattr => write!(f, "{}", "fgetxattr"),
            SyscallName::Listxattr => write!(f, "{}", "listxattr"),
            SyscallName::Llistxattr => write!(f, "{}", "llistxattr"),
            SyscallName::Flistxattr => write!(f, "{}", "flistxattr"),
            SyscallName::Removexattr => write!(f, "{}", "removexattr"),
            SyscallName::Lremovexattr => write!(f, "{}", "lremovexattr"),
            SyscallName::Fremovexattr => write!(f, "{}", "fremovexattr"),
            SyscallName::Tkill => write!(f, "{}", "tkill"),
            SyscallName::Time => write!(f, "{}", "time"),
            SyscallName::Futex => write!(f, "{}", "futex"),
            SyscallName::SchedSetaffinity => write!(f, "{}", "schedsetaffinity"),
            SyscallName::SchedGetaffinity => write!(f, "{}", "schedgetaffinity"),
            SyscallName::SetThreadArea => write!(f, "{}", "setthreadarea"),
            SyscallName::IoSetup => write!(f, "{}", "iosetup"),
            SyscallName::IoDestroy => write!(f, "{}", "iodestroy"),
            SyscallName::IoGetevents => write!(f, "{}", "iogetevents"),
            SyscallName::IoSubmit => write!(f, "{}", "iosubmit"),
            SyscallName::IoCancel => write!(f, "{}", "iocancel"),
            SyscallName::GetThreadArea => write!(f, "{}", "getthreadarea"),
            SyscallName::LookupDcookie => write!(f, "{}", "lookupdcookie"),
            SyscallName::EpollCreate => write!(f, "{}", "epollcreate"),
            SyscallName::EpollCtlPld => write!(f, "{}", "epollctlpld"),
            SyscallName::EpollWaitPld => write!(f, "{}", "epollwaitpld"),
            SyscallName::RemapFilePages => write!(f, "{}", "remapfilepages"),
            SyscallName::Getdents64 => write!(f, "{}", "getdents64"),
            SyscallName::SetTidAddress => write!(f, "{}", "settidaddress"),
            SyscallName::RestartSyscall => write!(f, "{}", "restartsyscall"),
            SyscallName::Semtimedop => write!(f, "{}", "semtimedop"),
            SyscallName::Fadvise64 => write!(f, "{}", "fadvise64"),
            SyscallName::TimerCreate => write!(f, "{}", "timercreate"),
            SyscallName::TimerSettime => write!(f, "{}", "timersettime"),
            SyscallName::TimerGettime => write!(f, "{}", "timergettime"),
            SyscallName::TimerGetoverrun => write!(f, "{}", "timergetoverrun"),
            SyscallName::TimerDelete => write!(f, "{}", "timerdelete"),
            SyscallName::ClockSettime => write!(f, "{}", "clocksettime"),
            SyscallName::ClockGettime => write!(f, "{}", "clockgettime"),
            SyscallName::ClockGetres => write!(f, "{}", "clockgetres"),
            SyscallName::ClockNanosleep => write!(f, "{}", "clocknanosleep"),
            SyscallName::ExitGroup => write!(f, "{}", "exitgroup"),
            SyscallName::EpollWait => write!(f, "{}", "epollwait"),
            SyscallName::EpollCtl => write!(f, "{}", "epollctl"),
            SyscallName::Tgkill => write!(f, "{}", "tgkill"),
            SyscallName::Utimes => write!(f, "{}", "utimes"),
            SyscallName::Vserver => write!(f, "{}", "vserver"),
            SyscallName::Mbind => write!(f, "{}", "mbind"),
            SyscallName::SetMempolicy => write!(f, "{}", "setmempolicy"),
            SyscallName::GetMempolicy => write!(f, "{}", "getmempolicy"),
            SyscallName::MqOpen => write!(f, "{}", "mqopen"),
            SyscallName::MqUnlink => write!(f, "{}", "mqunlink"),
            SyscallName::MqTimedsend => write!(f, "{}", "mqtimedsend"),
            SyscallName::MqTimedreceive => write!(f, "{}", "mqtimedreceive"),
            SyscallName::MqNotify => write!(f, "{}", "mqnotify"),
            SyscallName::MqGetsetattr => write!(f, "{}", "mqgetsetattr"),
            SyscallName::KexecLoad => write!(f, "{}", "kexecload"),
            SyscallName::Waitid => write!(f, "{}", "waitid"),
            SyscallName::AddKey => write!(f, "{}", "addkey"),
            SyscallName::RequestKey => write!(f, "{}", "requestkey"),
            SyscallName::Keyctl => write!(f, "{}", "keyctl"),
            SyscallName::IoprioSet => write!(f, "{}", "ioprioset"),
            SyscallName::IoprioGet => write!(f, "{}", "ioprioget"),
            SyscallName::InotifyInit => write!(f, "{}", "inotifyinit"),
            SyscallName::InotifyAddWatch => write!(f, "{}", "inotifyaddwatch"),
            SyscallName::InotifyRmWatch => write!(f, "{}", "inotifyrmwatch"),
            SyscallName::MigratePages => write!(f, "{}", "migratepages"),
            SyscallName::Openat => write!(f, "{}", "openat"),
            SyscallName::Mkdirat => write!(f, "{}", "mkdirat"),
            SyscallName::Mknodat => write!(f, "{}", "mknodat"),
            SyscallName::Fchownat => write!(f, "{}", "fchownat"),
            SyscallName::Futimesat => write!(f, "{}", "futimesat"),
            SyscallName::Newfstatat => write!(f, "{}", "newfstatat"),
            SyscallName::Unlinkat => write!(f, "{}", "unlinkat"),
            SyscallName::Renameat => write!(f, "{}", "renameat"),
            SyscallName::Linkat => write!(f, "{}", "linkat"),
            SyscallName::Symlinkat => write!(f, "{}", "symlinkat"),
            SyscallName::Readlinkat => write!(f, "{}", "readlinkat"),
            SyscallName::Fchmodat => write!(f, "{}", "fchmodat"),
            SyscallName::Faccessat => write!(f, "{}", "faccessat"),
            SyscallName::Pselect6 => write!(f, "{}", "pselect6"),
            SyscallName::Ppoll => write!(f, "{}", "ppoll"),
            SyscallName::Unshare => write!(f, "{}", "unshare"),
            SyscallName::SetRobustList => write!(f, "{}", "setrobustlist"),
            SyscallName::GetRobustList => write!(f, "{}", "getrobustlist"),
            SyscallName::Splice => write!(f, "{}", "splice"),
            SyscallName::Tee => write!(f, "{}", "tee"),
            SyscallName::SyncFileRange => write!(f, "{}", "syncfilerange"),
            SyscallName::Vmsplice => write!(f, "{}", "vmsplice"),
            SyscallName::MovePages => write!(f, "{}", "movepages"),
            SyscallName::Utimensat => write!(f, "{}", "utimensat"),
            SyscallName::EpollPwait => write!(f, "{}", "epollpwait"),
            SyscallName::Signalfd => write!(f, "{}", "signalfd"),
            SyscallName::TimerfdCreate => write!(f, "{}", "timerfdcreate"),
            SyscallName::Eventfd => write!(f, "{}", "eventfd"),
            SyscallName::Fallocate => write!(f, "{}", "fallocate"),
            SyscallName::TimerfdSettime => write!(f, "{}", "timerfdsettime"),
            SyscallName::TimerfdGettime => write!(f, "{}", "timerfdgettime"),
            SyscallName::Accept4 => write!(f, "{}", "accept4"),
            SyscallName::Signalfd4 => write!(f, "{}", "signalfd4"),
            SyscallName::Eventfd2 => write!(f, "{}", "eventfd2"),
            SyscallName::EpollCreate1 => write!(f, "{}", "epollcreate1"),
            SyscallName::Dup3 => write!(f, "{}", "dup3"),
            SyscallName::Pipe2 => write!(f, "{}", "pipe2"),
            SyscallName::InotifyInit1 => write!(f, "{}", "inotifyinit1"),
            SyscallName::Preadv => write!(f, "{}", "preadv"),
            SyscallName::Pwritev => write!(f, "{}", "pwritev"),
            SyscallName::RtTgsigqueueinfo => write!(f, "{}", "rttgsigqueueinfo"),
            SyscallName::PerfEventOpen => write!(f, "{}", "perfeventopen"),
            SyscallName::Recvmmsg => write!(f, "{}", "recvmmsg"),
            SyscallName::FanotifyInit => write!(f, "{}", "fanotifyinit"),
            SyscallName::FanotifyMark => write!(f, "{}", "fanotifymark"),
            SyscallName::Prlimit64 => write!(f, "{}", "prlimit64"),
            SyscallName::NameToHandleAt => write!(f, "{}", "nametohandleat"),
            SyscallName::OpenByHandleAt => write!(f, "{}", "openbyhandleat"),
            SyscallName::ClockAdjtime => write!(f, "{}", "clockadjtime"),
            SyscallName::Syncfs => write!(f, "{}", "syncfs"),
            SyscallName::Sendmmsg => write!(f, "{}", "sendmmsg"),
            SyscallName::Setns => write!(f, "{}", "setns"),
            SyscallName::Getcpu => write!(f, "{}", "getcpu"),
            SyscallName::ProcessVmReadv => write!(f, "{}", "processvmreadv"),
            SyscallName::ProcessVmWritev => write!(f, "{}", "processvmwritev"),
            SyscallName::Kcmp => write!(f, "{}", "kcmp"),
            SyscallName::FinitModule => write!(f, "{}", "finitmodule"),
            SyscallName::SchedSetattr => write!(f, "{}", "schedsetattr"),
            SyscallName::SchedGetattr => write!(f, "{}", "schedgetattr"),
            SyscallName::Renameat2 => write!(f, "{}", "renameat2"),
            SyscallName::Seccomp => write!(f, "{}", "seccomp"),
            SyscallName::Getrandom => write!(f, "{}", "getrandom"),
            SyscallName::MemfdCreate => write!(f, "{}", "memfdcreate"),
            SyscallName::KexecFileLoad => write!(f, "{}", "kexecfileload"),
            SyscallName::Bpf => write!(f, "{}", "bpf"),
            SyscallName::Execveat => write!(f, "{}", "execveat"),
            SyscallName::Userfaultfd => write!(f, "{}", "userfaultfd"),
            SyscallName::Membarrier => write!(f, "{}", "membarrier"),
            SyscallName::Mlock2 => write!(f, "{}", "mlock2"),
            SyscallName::CopyFileRange => write!(f, "{}", "copyfilerange"),
            SyscallName::Preadv2 => write!(f, "{}", "preadv2"),
            SyscallName::Pwritev2 => write!(f, "{}", "pwritev2"),
        }
    }
}
